import "./globals.css";
import { Noto_Serif } from "next/font/google";
import LayoutWrapper from "./components/LayoutWrapper";

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={notoSerif.className}
    >
      <body className="min-h-full flex flex-col"  cz-shortcut-listen="true">
        <LayoutWrapper>
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}